name: taskcluster extra workers
on: [push]
jobs:
  osx:
    runs-on: macos-10.15
    env:
      secret: ${{ secrets.SECRET }}
      TC_WORKER_TYPE: osx
      PATH: /usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin
    steps:
      - uses: actions/checkout@v2
      - run: curl -OL https://bootstrap.pypa.io/2.6/get-pip.py
      - run: sudo -H python get-pip.py
      - run: sudo -H pip install virtualenv==16.7.9
      - run: CI/start-worker.sh worker-$TC_WORKER_TYPE $TC_WORKER_TYPE
